language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: 7.0
    - php: 7.1
    - php: nightly

before_install:
    - composer self-update

install:
    - composer install --prefer-source

script:
    - php app/vendor/bin/phpunit
